### ISSUE TITLE
GD-243: CLI doesn't fail when test code throws errors

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#243] opened 2022-05-07 03:30 UTC
Hi,

As we discussed in a previous issue, you can run gdUnit3 tests in "Debug" mode (fails if the code throws an error).

How do I run it in this mode, when running the tests as part of a build? Currently, I'm using this code:

```
./Godot_v3.4.2-stable_linux_headless.64 -s addons/gdUnit3/bin/GdUnitCmdTool.gd --add tests/test_cases/gdunit
```

I just noticed that several tests are failing due to a refactoring change. (The game code is correct, but the test code refers to variables that no longer exist.) But, the build still passes, and shows that all tests are passing. Sure enough, if I use "Run tests" in Godot, I see everything pass; if I use "Debug tests," I see errors (not failures).

Is there a way to make the build fail in this scenario? I think a lot of other test frameworks (e.g. NUnit) return a status code on exit indicating a failure. That would be helpful here (tests look like they pass, but there are errors).

**Comment by MikeSchulze** [comment] 2022-05-07 08:02
hi thanks for reporting.

I have a few questions.
a) you running gd or c# tests
b) can you please attach a example test suite with the described issue
c) why you not use the provided runner script 'runtest.sh' ?
    The script executes the test in debug mode, this is need to collect failure lines.
   `$GODOT_BIN --no-window -s -d ./addons/gdUnit3/bin/GdUnitCmdTool.gd $*`


GdUnit3 differs between failures and errors.
failures means a test failure a assertion is failing
errors are often test interruptions or general compile errors.

And the tool is handling specific return codes as documented
https://mikeschulze.github.io/gdUnit3/advanced_testing/ci/#return-codes

**Comment by nightblade9** [comment] 2022-05-07 20:30
a) GDScript tests
b) Here's a simple example that reproduces the problem. Any test accessing a field that doesn't exist, reproduces this problem.

```gdscript
func test_stuff():
  var button = Button.instance()
  button.field_that_doesnt_exist = 39
  button.this_method_doesnt_exist() # probably also reproduces it
```

c) I don't seem to have that file in my repo. I upgraded gdUnit3 to v2.0.0 yesterday. Running this script seems to halt execution and prompt for user interaction. That doesn't make sense in a CI environment (e.g. GitHub build). Even if I pick 'c' to continue, the final result still says all tests passed. Plus, `$?` is 0.

d) v2.0.0

I don't think it's a duplicate. My comments on GD-112 were about running tests in-editor. This is about running them from the CLI as part of a build process.

**Comment by MikeSchulze** [comment] 2022-05-08 08:00
Hi @nightblade9 

this is a duplicate of GD-112. 
As I explained in this issue, Godot does not have an API like try catch to handle such errors.
You can reproduce the problem yourself by creating a simple scene with a button to run this code
```
func _on_Button_pressed():
	prints("a")
	Resource.new().get_foo()
	prints("b")
```

When you execute the scene via 
`Godot res://test.tscn` without debugging, then you will see that the error is only printed in the system output, but not handled by the scene itself.
At runtime without debug information, a failed function call always ends with the execution exiting at the error and returning without any error handling.
The Godot API has no function to catch such errors!
It also has no function to access the error printed to the console.

If you use the debug function `Godot -d res://test.tscn`, you will see that Godot also stops on an error.
So there is currently no way to handle such errors with GdUnit3, this is a general problem of the GdScript API.

Translated with www.DeepL.com/Translator (free version)

close as dupplicte to GD-112

**Closed by MikeSchulze** 2022-05-08 08:00 UTC
Labels: infos requested

**Comment by nightblade9** [comment] 2022-05-09 17:08
That's disappointing, but understandable. I checked how GUT does this - if you have a crashing test, it shows up with a warning (test doesn't assert) or with other assertions, but no other indication that it crashed.

This doesn't have a good solution for CI systems (run all tests and make sure it all passes). At this point, I guess my best choice is to run the tests manually before checking in changes. Hopefully Godot 4.1 with C# consumable as a NuGet package will allow me to use NUnit instead to test, at least, non-Godot-touching things...

**Comment by MikeSchulze** [comment] 2022-05-09 18:07
I verified your GUT assertion and can't agree. 
GUT also stops at the corrupted line when running in debug mode and ignores such errors when running in non-debug mode.

Using this simple test
```
extends "res://addons/gut/test.gd"

func test_one():
	assert_ne("five", "five", "This should fail")

func test_fails():
  var x = 0
  assert_eq(x, 0)
  Resource.new().foo()
  assert_eq(1, 2)
```

reports 
```

res://test/xxx/test_sample_two.gd
* test_fails
    [Passed]:  [0] expected to equal [0]:
SCRIPT ERROR: test_fails: Invalid call. Nonexistent function 'foo' in base 'Resource'.
          At: res://test/xxx/test_sample_two.gd:10
* test_one
    [Failed]:  ["five"] expected to not equal ["five"]:  This should fail
      at line -1
1/2 passed.


*** Run Summary ***
res://test/xxx/test_sample_two.gd
- test_one
    [Failed]:  ["five"] expected to not equal ["five"]:  This should fail
          at line -1

Totals
Scripts:          1
Tests:            2
Passing asserts:  1
Failing asserts:  1
Pending:          0

1 passed 1 failed.  Tests finished in 0.3s

```

You can see the test `test_fails` is still passed.

But good news, I found a way to implement my own error handling to catch such errors and report them as errors.
It's currently in prototyping and needs to be optimized, but the solution will have an impact on the execution time of the tests.

**Comment by nightblade9** [comment] 2022-05-09 18:28
You have the same result as me when it comes to GUT. Here's how my test looked:

```
func test_error():
  var b = Button.new()
  b.quantum_state = "entangled"
  assert_eq(2 - 1, 1)
```

This froze on that line when running in-editor, and issued the warning about not asserting. The UI reports "1 passed, 0 failed."

Anyway, I'm glad to hear you found a solution that works. I would rather switch to C#, but that's not feasible so close to release.
