### ISSUE TITLE
Note: performance issue?

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#51] opened 2021-04-14 13:07 UTC
I'm testing with Godot-3.3-rc8 and ran into [Slow Create Resource Dialog in a project with a lot of class_names](https://github.com/godotengine/godot/issues/34205) having only this plugin.

We have ~240 `class_name` items.

![image](https://user-images.githubusercontent.com/371014/114714882-d278f480-9d32-11eb-9028-274a9fd705b4.png)

So this is not a bug but it takes ~10 sec to get this Resource dropdowns to open.

It seems not being fixed before Godot-4 :-(

**Comment by clemens-tolboom** [comment] 2021-04-14 13:12
Nice label ~"godot related issue"

**Comment by MikeSchulze** [comment] 2021-04-14 13:12
Thanks for reporting this.
You ok to close this because it is a Godot related bug and is not relates to GdUnit3 plugin?

**Comment by clemens-tolboom** [comment] 2021-04-14 13:14
Remove the bug label and yes OK to close.

**Closed** 2021-04-14 13:15 UTC
Labels: godot related issue

**Comment by clemens-tolboom** [comment] 2021-04-14 13:21
Wow ... it is only slow when the plugin is **not** enabled ... can you test that yourself.

**Comment by MikeSchulze** [comment] 2021-04-14 13:25
Ok, so it is reproducible by enabling/disabling the GdUnit3 plugin?
Can you please add the steps to reproduce.

**Comment by MikeSchulze** [comment] 2021-04-14 13:38
After a quick analysis, I suspect it's because I'm scanning for registered classes in my plugin.
```
var script_classes:Array = ProjectSettings.get_setting("_global_script_classes") as Array
```

Maybe this pre caches the classes. 

Can you try this as a workaround?

**Comment by clemens-tolboom** [comment] 2021-04-14 13:54
Having the plugin disabled/not enabled produce this (~20secs) issue.

After enabling the plugin performance improves by a factor of 10 (~2secs).

1. Enable gdUnit3
1. Open a Scene
1. Add a node
1. Set it's Material / Theme (just click the dropdown)
1. Disable gdUnit3
1. Set it's Material / Theme (just click the dropdown)

So this project is not the problem. It's Godot scanning for Resource files according to https://github.com/godotengine/godot/issues/34205
